package com.alsodeep.leetcode;

/**
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 * Created by alsodeep on 01/09/16.
 */
public class Task389 {

    public char findTheDifference(String s, String t) {

        char[] sString = s.toCharArray();
        char[] tString = t.toCharArray();

        if(s.length() > t.length()){
            return find(sString, tString);
        } else {
           return find(tString, sString);
            }
    }

    private char find(char[] longest, char[] shortest){

        char xorLongest = 0;
        char xorShortest = 0;

        for (int i = 0; i < longest.length; i++) {
            xorLongest = (char) (xorLongest ^ longest[i]);
        }

        for (int i = 0; i < shortest.length; i++) {
            xorShortest = (char) (xorShortest ^ shortest[i]);
        }
        char res = (char) (xorLongest ^ xorShortest);
        return res;
    }



    public static void main(String[] args){

        Task389 task = new Task389();
        task.findTheDifference("abd", "bbda");

    }

}
